version: '3.9'

services:
  collector-service:
    build: ./data_collector
    container_name: collector
    image: data_collector
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup/:/sys/fs/cgroup/
      - /proc/:/proc/
