version: '3.9'

services:
      
  database-service:
    image: questdb/questdb:latest
    hostname: questdb
    container_name: questdb
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8812:8812"
      - "9003:9003"
    volumes:
      - ./questDB:/root/.questdb/

  collector-service:
    build: ./data_collector
    container_name: collector
    image: data_collector
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup/:/sys/fs/cgroup/
      - /proc/:/proc/
    depends_on:
      - database-service


